In [1]:
import numpy as np

nums = [1,2,3,4,5]

arrayy1 = np.array(nums)
print(arrayy1)

[1 2 3 4 5]


In [2]:
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [3]:
one_array = np.ones(3)
print(one_array)

[1. 1. 1.]


In [4]:
range_array = np.arange(1,10,2)
print(range_array)

[1 3 5 7 9]


In [5]:
random_array = np.random.randint(1,100,5)
print(random_array)

[73 55 69 63 90]


In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.45174604 0.28663886 0.58346831]
 [0.86538559 0.59980041 0.15135816]
 [0.31841874 0.36134142 0.87307176]]


In [7]:
shape = range_array.shape
print(shape)

(5,)


In [8]:
size = range_array.size
print(size)

5


In [9]:
dtype = range_array.dtype
print(dtype)

int32


In [10]:
print(range_array.ndim)

1
